services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: campfire_connections.settings.local
      DJANGO_DEBUG: "true"
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0,web
    volumes:
      - .:/app
